import React from 'react';

import type { Metadata } from "next";

import PrivateWrapper from './_components/PrivateWrapper';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MainLayout = ({
  children
}: {
  children: React.ReactNode
}) => {
  return (
    <PrivateWrapper>
      {children}
    </PrivateWrapper>
  );
};

export default MainLayout;