import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Invitation | Central Sync Hub",
  description: "Generated by create next app",
};

const AuthLayout = ({
  children
}: {
  children: React.ReactNode
}) => {
  return (
    <>
      <main className='flex justify-center items-center h-full w-full'>
        {children}
      </main>
    </>
  );
};

export default AuthLayout;